language: php

php:
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION=dev-master

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer install
