security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
            logout:
                path: security_logout
                target: homepage